# Generated by Django 5.2.12 on 2026-03-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='location',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('P1', 'Critical'), ('P2', 'High'), ('P3', 'Medium'), ('P4', 'Low')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=10),
        ),
    ]
