# Generated by Django 4.2.9 on 2026-03-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('Critical', 'P1 - Critical'), ('High', 'P2 - High'), ('Medium', 'P3 - Medium'), ('Low', 'P4 - Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
    ]
