name: CI/CD Django Deployment

on:
  push:
    branches:
      - main

jobs:

 
  # CI JOB (VALIDATION)

  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install flake8 bandit
    
    - name: Run Flake8 (Code Quality)
      run: |
        flake8 . --exclude=venv,migrations --max-line-length=120 || true

    - name: Run Bandit (Security Scan)
      run: |
        bandit -r . -x venv,migrations || true

    - name: Django System Check
      run: |
        python manage.py check

  
  # CD JOB (DEPLOYMENT)

  deploy:
    needs: ci   # (runs only if CI passes)
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            script: |
            set -e

            cd ~/projects/incident-system

            git reset --hard
            git pull origin main

            source venv/bin/activate

            pip install -r requirements.txt

            python manage.py migrate

            python manage.py collectstatic --noinput

            sudo systemctl restart gunicorn
            sudo systemctl restart nginx